"""
radlearn/database/conversations.py
────────────────────────────────────
CRUD for conversations and messages tables.

Connection to system:
  - chat/engine.py creates a conversation on first question in a session.
  - chat/engine.py writes one user message and one assistant message per query.
  - Admin dashboard reads messages for the recent queries table.
  - The metrics columns (retrieval_time_ms, top_similarity_score, etc.)
    are populated on the assistant message so performance can be tracked.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from radlearn.database.client import execute_sql


# ── Conversations ─────────────────────────────────────────────────

def create_conversation(
    session_token: str = "",
    specialty_filter: str = "",
    project_id: str | None = None,
) -> dict:
    """
    Create a new conversation record (one per browser session in MVP).

    Args:
        session_token:    Random UUID string generated by the Streamlit session.
        specialty_filter: The specialty the user selected at start of session.
        project_id:       Optional ID of the project this conversation belongs to.

    Returns: the created conversation record.
    """
    record = {
        "id":               str(uuid.uuid4()),
        "user_id":          "",
        "session_token":    session_token,
        "specialty_filter": specialty_filter,
        "message_count":    0,
        "started_at":       _now(),
        "last_active_at":   _now(),
        "project_id":       project_id,
    }
    execute_sql(
        """
        INSERT INTO conversations
            (id, user_id, session_token, specialty_filter,
             message_count, started_at, last_active_at, project_id)
        VALUES
            (:id, :user_id, :session_token, :specialty_filter,
             :message_count, :started_at, :last_active_at, :project_id)
        """,
        record,
    )
    return record


def get_conversation(conversation_id: str) -> dict | None:
    rows = execute_sql(
        "SELECT * FROM conversations WHERE id = :id",
        {"id": conversation_id},
    )
    return rows[0] if rows else None


def end_conversation(conversation_id: str) -> None:
    """Mark conversation as ended (used when user clicks 'New conversation')."""
    execute_sql(
        "UPDATE conversations SET last_active_at = :t WHERE id = :id",
        {"t": _now(), "id": conversation_id},
    )


# ── Messages ──────────────────────────────────────────────────────

def create_message(
    conversation_id: str,
    role: str,
    content: str,
    message_index: int = 0,
    **kwargs,
) -> dict:
    """
    Insert a message (user question or assistant answer).

    Args:
        conversation_id: UUID of the parent conversation.
        role:            'user' or 'assistant'.
        content:         The raw text of the message.
        message_index:   Sequential position within the conversation.
        **kwargs:        Any additional columns to populate:
                            expanded_query, top_similarity_score,
                            chunks_retrieved, images_retrieved,
                            retrieval_time_ms, llm_time_ms, total_time_ms,
                            was_answered, llm_model

    Returns: the created message record.
    """
    record = {
        "id":                   str(uuid.uuid4()),
        "conversation_id":      conversation_id,
        "role":                 role,
        "content":              content,
        "expanded_query":       str(kwargs.get("expanded_query", "")),
        "top_similarity_score": float(kwargs.get("top_similarity_score", 0.0)),
        "chunks_retrieved":     int(kwargs.get("chunks_retrieved", 0)),
        "images_retrieved":     int(kwargs.get("images_retrieved", 0)),
        "retrieval_time_ms":    int(kwargs.get("retrieval_time_ms", 0)),
        "llm_time_ms":          int(kwargs.get("llm_time_ms", 0)),
        "total_time_ms":        int(kwargs.get("total_time_ms", 0)),
        "was_answered":         1 if kwargs.get("was_answered") else 0,
        "llm_model":            str(kwargs.get("llm_model", "gemini-1.5-flash")),
        "user_rating":          0,
        "was_helpful":          -1,
        "feedback_text":        "",
        "message_index":        message_index,
        "created_at":           _now(),
    }
    execute_sql(
        """
        INSERT INTO messages
            (id, conversation_id, role, content, expanded_query,
             top_similarity_score, chunks_retrieved, images_retrieved,
             retrieval_time_ms, llm_time_ms, total_time_ms,
             was_answered, llm_model, user_rating, was_helpful,
             feedback_text, message_index, created_at)
        VALUES
            (:id, :conversation_id, :role, :content, :expanded_query,
             :top_similarity_score, :chunks_retrieved, :images_retrieved,
             :retrieval_time_ms, :llm_time_ms, :total_time_ms,
             :was_answered, :llm_model, :user_rating, :was_helpful,
             :feedback_text, :message_index, :created_at)
        """,
        record,
    )

    # Increment conversation message count
    execute_sql(
        """
        UPDATE conversations
        SET message_count = message_count + 1, last_active_at = :t
        WHERE id = :id
        """,
        {"t": _now(), "id": conversation_id},
    )

    return record


def get_conversation_messages(conversation_id: str) -> list[dict]:
    """Return all messages in a conversation ordered by message_index."""
    return execute_sql(
        "SELECT * FROM messages WHERE conversation_id = :id ORDER BY message_index ASC",
        {"id": conversation_id},
    )

def get_message(message_id: str) -> dict | None:
    """Return a single message by ID."""
    rows = execute_sql(
        "SELECT * FROM messages WHERE id = :id",
        {"id": message_id},
    )
    return rows[0] if rows else None

def get_message_by_index(conversation_id: str, index: int) -> dict | None:
    """Return a single message by its index within a conversation."""
    rows = execute_sql(
        "SELECT * FROM messages WHERE conversation_id = :id AND message_index = :index",
        {"id": conversation_id, "index": index},
    )
    return rows[0] if rows else None


def get_next_message_index(conversation_id: str) -> int:
    """Return the next available message_index for a conversation."""
    rows = execute_sql(
        "SELECT MAX(message_index) AS max_idx FROM messages WHERE conversation_id = :id",
        {"id": conversation_id},
    )
    max_idx = rows[0]["max_idx"] if rows and rows[0]["max_idx"] is not None else -1
    return max_idx + 1


def update_message_feedback(
    message_id: str,
    rating: int,
    was_helpful: bool,
    feedback_text: str = "",
) -> None:
    """
    Store user feedback on an assistant message.

    Args:
        message_id:    UUID of the assistant message being rated.
        rating:        Integer 1–5 star rating.
        was_helpful:   True/False thumbs.
        feedback_text: Optional free-text comment.
    """
    execute_sql(
        """
        UPDATE messages
        SET user_rating = :r, was_helpful = :h, feedback_text = :t
        WHERE id = :id
        """,
        {
            "r":  rating,
            "h":  1 if was_helpful else 0,
            "t":  feedback_text,
            "id": message_id,
        },
    )


def get_recent_queries(limit: int = 20) -> list[dict]:
    """Return the most recent user messages for the admin dashboard."""
    return execute_sql(
        """
        SELECT m.content, m.top_similarity_score, m.was_answered,
               m.user_rating, m.total_time_ms, m.created_at,
               c.specialty_filter
        FROM messages m
        JOIN conversations c ON m.conversation_id = c.id
        WHERE m.role = 'user'
        ORDER BY m.created_at DESC
        LIMIT :limit
        """,
        {"limit": limit},
    )

def get_all_conversations(project_id: str | None = None) -> list[dict]:
    """Return all conversations, with their latest message snippet."""
    if project_id:
        return execute_sql(
            """
            SELECT c.*, 
                   (SELECT content FROM messages WHERE conversation_id = c.id AND role = 'user' ORDER BY message_index ASC LIMIT 1) as first_message
            FROM conversations c
            WHERE c.project_id = :project_id
            ORDER BY c.last_active_at DESC
            """,
            {"project_id": project_id}
        )
    else:
        return execute_sql(
            """
            SELECT c.*, 
                   (SELECT content FROM messages WHERE conversation_id = c.id AND role = 'user' ORDER BY message_index ASC LIMIT 1) as first_message
            FROM conversations c
            WHERE c.project_id IS NULL
            ORDER BY c.last_active_at DESC
            """
        )


# ── Helpers ───────────────────────────────────────────────────────

def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
def delete_conversation(conversation_id: str) -> None:
    """Delete a conversation and all its associated messages and citations."""
    messages = execute_sql("SELECT id FROM messages WHERE conversation_id = :id", {"id": conversation_id})
    for msg in messages:
        execute_sql("DELETE FROM citations WHERE message_id = :id", {"id": msg["id"]})
    execute_sql("DELETE FROM messages WHERE conversation_id = :id", {"id": conversation_id})
    execute_sql("DELETE FROM conversations WHERE id = :id", {"id": conversation_id})
